package com.njit.cookbook.sql;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import cn.njit.cookbook.model.CommentBean;
import cn.njit.cookbook.model.FoodBean;
import cn.njit.cookbook.model.UserBean;

import com.njit.cookbook.sql.CommentBeanDao;
import com.njit.cookbook.sql.FoodBeanDao;
import com.njit.cookbook.sql.UserBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig commentBeanDaoConfig;
    private final DaoConfig foodBeanDaoConfig;
    private final DaoConfig userBeanDaoConfig;

    private final CommentBeanDao commentBeanDao;
    private final FoodBeanDao foodBeanDao;
    private final UserBeanDao userBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        commentBeanDaoConfig = daoConfigMap.get(CommentBeanDao.class).clone();
        commentBeanDaoConfig.initIdentityScope(type);

        foodBeanDaoConfig = daoConfigMap.get(FoodBeanDao.class).clone();
        foodBeanDaoConfig.initIdentityScope(type);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        commentBeanDao = new CommentBeanDao(commentBeanDaoConfig, this);
        foodBeanDao = new FoodBeanDao(foodBeanDaoConfig, this);
        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);

        registerDao(CommentBean.class, commentBeanDao);
        registerDao(FoodBean.class, foodBeanDao);
        registerDao(UserBean.class, userBeanDao);
    }
    
    public void clear() {
        commentBeanDaoConfig.clearIdentityScope();
        foodBeanDaoConfig.clearIdentityScope();
        userBeanDaoConfig.clearIdentityScope();
    }

    public CommentBeanDao getCommentBeanDao() {
        return commentBeanDao;
    }

    public FoodBeanDao getFoodBeanDao() {
        return foodBeanDao;
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

}
